spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/hotel_mongo?authSource=admin
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5435/hotel_db
    username: postgres
    password: postgres
    hikari:
      schema: hotel_app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_app_schema
      connection-timeout: 10000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  logging:
    level:
      root: INFO
      org.hibernate: DEBUG
      org.springframework: DEBUG
app:
  security:
    type: db
  kafka:
    kafkaUserTopic: "user-topic"
    kafkaBookingTopic: "booking-topic"
    kafkaGroupId: "group-id"
