name: CI - Gradle Build & Test

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew --no-daemon clean test

      - name: Publish test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: |
            build/test-results/test/**
            build/reports/tests/test/**
