
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Сборка проекта
        run: mvn clean package -DskipTests

      - name: Логин в DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка Docker-образа
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hotel-reservation:latest .

      - name: Публикация Docker-образа
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hotel-reservation:latest